### ISSUE TITLE
File "csamtools.pyx", line 763, in csamtools.Samfile._open (pysam/csamtools.c:8313)

### ISSUE THREAD

**Issue by brianpenghe** [brianpenghe/bamsam-scripts#2]
Traceback (most recent call last):
  File "/../home/georgi/code/bamPreprocessing.py", line 145, in <module>
    main(sys.argv)
  File "/../home/georgi/code/bamPreprocessing.py", line 31, in main
    outfile = pysam.Samfile(outputfilename, "wb", header=outheader)
  File "csamtools.pyx", line 597, in csamtools.Samfile.__cinit__ (pysam/csamtools.c:6505)
  File "csamtools.pyx", line 763, in csamtools.Samfile._open (pysam/csamtools.c:8313)

IOError: could not open file `../13985-50mers-W6i-1-TopHat-2.0.8-ENSEMBL66/accepted_hits.preprocessed.bam`

**Comment by brianpenghe** [comment]
This error could have been generated by attempting to create a file at a location where permission to write is denied.
