### ISSUE TITLE
 IndexError: list index out of range

### ISSUE THREAD

**Issue by brianpenghe** [brianpenghe/bamsam-scripts#5]
Traceback (most recent call last):
  File "/../georgi/code/makewigglefromBAM-NH.py", line 413, in <module>
    run()
  File "/../georgi/code/makewigglefromBAM-NH.py", line 186, in run
    reads = int(fields[2])
IndexError: list index out of range

**Comment by brianpenghe** [comment]
Georgi:
Has the pysam version changed somehow by any chance?

This is what that function should output (it does that on the system here):

for chrStats in pysam.idxstats(BAM):
          print chrStats

['chr10', '129993255', '3906907', '0']
....

This is what I get for this file on pongo:

c
h
r
1
    
1
9
7
1
9
5
4
3
2
    
9
3
7
5
4
    
0

**Comment by brianpenghe** [comment]
Henry:
The default output from samtools commands run via the dispatcher method has changed:

https://github.com/pysam-developers/pysam/issues/245

This is actually a move in the right direction, I just wish that the packagers would have made a more vocal announcement of the change during the upgrade process.

The idea is that pysam command line tools which send to stdout and stderr break in environments where stdout and stderr is captured and potentially mangled in some way.  By returning a string, for every tool, it unifies the output into one format that can be dealt with by the developer at presentation time.

Unfortunately, now a bunch of tools are probably broken and will need adjustments.

As a side note, samtools sort and as a consequence, pysam.sort() has changed the way it writes the sorted bam file.  You now have to specify the output file name via the -o switch or redirect stdout to a file. They also enabled threading.

**Comment by brianpenghe** [comment]
This problem has been fixed now.
